### ISSUE TITLE
Does not work on Manjaro

### ISSUE THREAD

**Issue by jclsn** [psifidotos/kwinscript-window-colors#1]
The panel nor the dock are changing their colors. Why could this be?

**Comment by psifidotos** [comment]
Have you enabled it from plasma systemsettings? and relogin to Plasma afterwards?

**Comment by jclsn** [comment]
You mean enabled the KWin script?

**Comment by psifidotos** [comment]
yes, and relogin afterwards in order to be activated

**Comment by jclsn** [comment]
Yes, I have done that many times

**Comment by psifidotos** [comment]
Show me a screenshot of your advanced settings in Latte, Appearance tab

**Comment by jclsn** [comment]
![image](https://user-images.githubusercontent.com/19779511/77243958-36081f80-6c10-11ea-900d-89029ed112fd.png)

**Comment by psifidotos** [comment]
Can you send me your Latte layout to make sure that this is not an issue with specific options?

**Comment by jclsn** [comment]
What do you mean by layout? I have already tried to change it to a panel and checked and unchecked every checkbox that seemed relevant.

**Comment by psifidotos** [comment]
Right click dock -> Dock Settings -> Layouts -> Configure Layouts...

Select the layout you are using, Export...
and send here the extracted ".layout.latte" file.

**Comment by jclsn** [comment]
[Standard.layout.latte.zip](https://github.com/psifidotos/kwinscript-window-colors/files/4366285/Standard.layout.latte.zip)

**Comment by psifidotos** [comment]
It is just a matter of settings you chose:

You need to enable also: Appearance -> Background -> Dynamic Visibility -> Prefer opaque background when touching any window

is that what you are trying to achieve?

**Comment by jclsn** [comment]
The setting you suggested does not solve my issue. It just makes the dock opaque instead of transparent. It does changes nothing about the color script. Can you please wait for me to confirm your solution before you close the issue?

**Comment by psifidotos** [comment]
It works perfectly in my system, it is not the script, as long as it works for panels it is not the script.

Can you describe what you are trying to achieve?

1. When the background will not be visible and when it will be visible? 
2.Your colors settings are set ok

**Comment by jclsn** [comment]
I want that the color of my panel changes according to the window that touches it and that does not happen. My panel always stays the same. The dock also does not change its color. It only changes to transparent when there is not window under it. 

![image](https://user-images.githubusercontent.com/19779511/77265003-de16fa80-6c9b-11ea-8f01-69b336ca12c8.png)


![image](https://user-images.githubusercontent.com/19779511/77264955-c2abef80-6c9b-11ea-9e7f-c69f942d59ed.png)



But I want my panel to behave like you showcased [https://www.youtube.com/watch?v=JVbIuZp3VFQ&feature=youtu.be](https://www.youtube.com/watch?v=JVbIuZp3VFQ&feature=youtu.be)

Could it be that this is blocked by some KDE setting?

**Comment by psifidotos** [comment]
https://m.youtube.com/watch?v=UTRtrNiJnkM have you manually assign different color schemes to your apps, like the video describes?

**Comment by jclsn** [comment]
It works for the dock now, but not for the panel. I also thought that this would work without having to manually set titlebar colors for every window. This was not written anywhere. I have the same titlebar color everywhere and I am using Vivaldi browser, which has the same color changing feature. It did not change to the color from Vivaldi and thus I was wondering

![image](https://user-images.githubusercontent.com/19779511/77298040-7c31b180-6cea-11ea-9885-283b12bdb71a.png)

**Comment by psifidotos** [comment]
the layout you sent me did not have a top panel in it... It is again a matter of settings, can you send the layout containing your top panel?

Concerning the fact that the user needs to set manually titlebar colors for its apps, this is the current limit of the plasma/kwin technology. For this to be solved,we would need a new decoration e.g. Breeze/SierraBreeze etc... that is autoupdating the window titlebar colorscheme.. Latte is already prepared for this but no decoration coders have tried to implement such thing.

**Comment by jclsn** [comment]
So you have to make a new panel from Latte? 

Yeah I know the KDE developers are kind of slow about innovations. But given it is a huge system with lots of features, I forgive them

**Comment by psifidotos** [comment]
> So you have to make a new panel from Latte?
> 

No, I just need to see your Apperance settings for your top panel

> Yeah I know the KDE developers are kind of slow about innovations. But given it is a huge system with lots of features, I forgive them

Plasma is an open source / volunteer driven project. We all need to help or need to learn how to help.

**Comment by jclsn** [comment]
I am using the normal KDE panel. I have not made it from Latte. It does not have appearance settings. Just the usual Plasma style in system settings. Ist hat what you mean?

> Plasma is an open source / volunteer driven project. We all need to help or need to learn how to help.

Sure, that is what I meant

**Comment by psifidotos** [comment]
If you want same coloring functionality for your top panel then you need to remove the top plasma panel and add a new Latte panel

**Comment by jclsn** [comment]
Why is the script changing the icons like this?


![image](https://im6.ezgif.com/tmp/ezgif-6-4093a91657ee.gif)

**Comment by psifidotos** [comment]
because it can not do otherwise...
Applets must be LatteColoring capable... so you can use Window Title, Window Buttons, Window AppMenu out of the box, for them you dont need to adjust anything.

for applets that you  dont want to be colored you must read: http://psifidotos.blogspot.com/2019/02/latte-and-colors-tale.html and it says there how to disable the autocoloring for specific applets

and for the systray the only solution is: https://github.com/psifidotos/plasma-systray-latte-tweaks

- - -- - - - 

Nothing else can be done until Plasma provides a mechanism/way to do this officialy...
You can request from plasma devs to provide such solution...

**Comment by jclsn** [comment]
So you can't turn off coloring for all of them? :/ Oh yes you can :) I don't need this anyway

Thank you! And thank you also for having done so much great work! I think this really is an amazing feature to make KDE more modern. I will file a few feature requests, when I find the time. But honestly all of this tweaking is keeping me from studying :D
