### ISSUE TITLE
Question: is this script sill necessary with current Plasma and latte?

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/kwinscript-window-colors#2]
I noticed, that regardless if the script is on or off, the upper panel is colorized properly after the titlebar color, when I set Appearance->Colors->Touching. This of course works only with Breeze aurorae theme.

Has latte gained this functionality so the script is not needed? Or maybe Plasma developed so it would work regardless of the script? Or maybe script allows for additional tweaks that I don't know of?

Also, how did you make the windows to have no borders/frame? Currently, when I color the window, Breeze Aurorae theme always adds some border, so when changing colors, this border stands out even more.

And so far, I was changing colors by modifying kwin settings for given app. I have no colors as you show on your videos and I feel I'm missing something.

**Comment by psifidotos** [comment]
1. The script is still needed, if you disable it you need to relogin in order to be truly disabled.
2. Aurorare themes I don't know how they work but because many of their parts do not work correctly I don't use them. I am using only c++ decorations such Breeze, Sierra Breeze etc... 
3. To activate borderless maximized windows in Latte:
https://userbase.kde.org/LatteDock/FAQ#Latte_v0.8_deactivates_Borderless_Maximized_Windows_from_Active_Window_Control_plasmoid.2C_what_can_I_do_.3F

**Comment by michaldybczak** [comment]
Ah, right. Relogging makes the coloring by touch inactive. Activating the scrip starts it immediately thou. OK, that is clear. Thanks.

How about colors? I can't find any colors like yours. Most of color schemes are simply white, black or variations, with slight coloring, but nothing striking out. So most of the themes I choose won't change anything because they will use standard breeze color for titlebar.

I tried to find Sierra Breeze aurorae but nothing comes out. In fact, till now I thought there is only one C++ theme - Breeze. There are many themes with breeze in name but they are still the usual themes, so there is no way to distinguish those that will work.

As to the borderless windows - it doesn't work. I already have this marked and it only deactivates titlebar in maximized mode, which is awesome, but breeze aurorae theme still applies quite thick borders without possibility to turn them off

By the way, when I came to Layout Options page, I got warning that the layout is broken. I had the same problem with the old one, so I created it anew and surprise, surprise, it gets broken again. 

Maybe one of the events that crashes latte causes that? It's pointless to fix that, because layout works and I have no desire to built anew again and again - this takes too much time and I see no reason to change that. Or maybe this makes the borderless option not to strip borders for breeze theme?

Or maybe you got me wrong? By borders I mean WINDOW BORDERS, not the titlebar. So left, right and bottom lines areound the window.. Or, again, the borders were changed between time you did the video and now?

So for example, when I use light breeze on Spotify it looks weird:

![Screenshot_20200420_151316](https://user-images.githubusercontent.com/10132958/79755550-99719400-8319-11ea-9749-c9435bf6b56a.jpg)

That is why I prefer to change it's color to dark. Some windows don't seem to have borders thou. So why some have them and others don't?

**Comment by psifidotos** [comment]
**Color Schemes:**
https://www.pling.com/p/1293988
and I also create my own through **Plasma SystemSettings-> Colors**
I just use the Breeze ColorScheme and I change only the TitleBar Background and TextColor and I save it with a different name afterwards, for example Breeze-LibreOffice, Breeze-Darkish etc...

**Disable Window Borders:**
![image](https://user-images.githubusercontent.com/2216474/79755391-b611ca00-8321-11ea-818f-d2a05bc78d9c.png)

**Comment by michaldybczak** [comment]
Thanks! That explains it. As to borders, now it works! As usual, option where no one would look for, typical Plasma ;).
All good and explained now. Thank you again!
